# Generated by Django 4.1.7 on 2023-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=1024)),
                ("text_response", models.TextField(max_length=1024)),
                ("image_response", models.TextField(max_length=1024)),
            ],
        ),
    ]
