# Generated by Django 4.1.7 on 2023-03-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="image_response",
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
